//
// Generated file. Do not edit manually.
// Generator : F:\DevWork\Core\CodeGen\ReposGen\UcdScripts\UcdScriptGen.cs
//

using System.Collections.Generic;

namespace ecl.Unicode {
	partial class XUtil {
		private static KeyValuePair<string,WritingScript>[] GetScriptValues() {
			return new[] {
				new KeyValuePair<string,WritingScript>( "Adlm", WritingScript.Adlam ),
				new KeyValuePair<string,WritingScript>( "Afak", WritingScript.Afaka ),
				new KeyValuePair<string,WritingScript>( "Aghb", WritingScript.CaucasianAlbanian ),
				new KeyValuePair<string,WritingScript>( "Caucasian_Albanian", WritingScript.CaucasianAlbanian ),
				new KeyValuePair<string,WritingScript>( "Ahom", WritingScript.Ahom ),
				new KeyValuePair<string,WritingScript>( "Arab", WritingScript.Arabic ),
				new KeyValuePair<string,WritingScript>( "Arabic", WritingScript.Arabic ),
				new KeyValuePair<string,WritingScript>( "Aran", WritingScript.ArabicNastaliq ),
				new KeyValuePair<string,WritingScript>( "Armi", WritingScript.ImperialAramaic ),
				new KeyValuePair<string,WritingScript>( "Imperial_Aramaic", WritingScript.ImperialAramaic ),
				new KeyValuePair<string,WritingScript>( "Armn", WritingScript.Armenian ),
				new KeyValuePair<string,WritingScript>( "Armenian", WritingScript.Armenian ),
				new KeyValuePair<string,WritingScript>( "Avst", WritingScript.Avestan ),
				new KeyValuePair<string,WritingScript>( "Avestan", WritingScript.Avestan ),
				new KeyValuePair<string,WritingScript>( "Bali", WritingScript.Balinese ),
				new KeyValuePair<string,WritingScript>( "Balinese", WritingScript.Balinese ),
				new KeyValuePair<string,WritingScript>( "Bamu", WritingScript.Bamum ),
				new KeyValuePair<string,WritingScript>( "Bamum", WritingScript.Bamum ),
				new KeyValuePair<string,WritingScript>( "Bass", WritingScript.BassaVah ),
				new KeyValuePair<string,WritingScript>( "Bassa_Vah", WritingScript.BassaVah ),
				new KeyValuePair<string,WritingScript>( "Batk", WritingScript.Batak ),
				new KeyValuePair<string,WritingScript>( "Batak", WritingScript.Batak ),
				new KeyValuePair<string,WritingScript>( "Beng", WritingScript.Bengali ),
				new KeyValuePair<string,WritingScript>( "Bengali", WritingScript.Bengali ),
				new KeyValuePair<string,WritingScript>( "Bhks", WritingScript.Bhaiksuki ),
				new KeyValuePair<string,WritingScript>( "Blis", WritingScript.Blissymbols ),
				new KeyValuePair<string,WritingScript>( "Bopo", WritingScript.Bopomofo ),
				new KeyValuePair<string,WritingScript>( "Bopomofo", WritingScript.Bopomofo ),
				new KeyValuePair<string,WritingScript>( "Brah", WritingScript.Brahmi ),
				new KeyValuePair<string,WritingScript>( "Brahmi", WritingScript.Brahmi ),
				new KeyValuePair<string,WritingScript>( "Brai", WritingScript.Braille ),
				new KeyValuePair<string,WritingScript>( "Braille", WritingScript.Braille ),
				new KeyValuePair<string,WritingScript>( "Bugi", WritingScript.Buginese ),
				new KeyValuePair<string,WritingScript>( "Buginese", WritingScript.Buginese ),
				new KeyValuePair<string,WritingScript>( "Buhd", WritingScript.Buhid ),
				new KeyValuePair<string,WritingScript>( "Buhid", WritingScript.Buhid ),
				new KeyValuePair<string,WritingScript>( "Cakm", WritingScript.Chakma ),
				new KeyValuePair<string,WritingScript>( "Chakma", WritingScript.Chakma ),
				new KeyValuePair<string,WritingScript>( "Cans", WritingScript.CanadianAboriginal ),
				new KeyValuePair<string,WritingScript>( "Canadian_Aboriginal", WritingScript.CanadianAboriginal ),
				new KeyValuePair<string,WritingScript>( "Cari", WritingScript.Carian ),
				new KeyValuePair<string,WritingScript>( "Carian", WritingScript.Carian ),
				new KeyValuePair<string,WritingScript>( "Cham", WritingScript.Cham ),
				new KeyValuePair<string,WritingScript>( "Cher", WritingScript.Cherokee ),
				new KeyValuePair<string,WritingScript>( "Cherokee", WritingScript.Cherokee ),
				new KeyValuePair<string,WritingScript>( "Cirt", WritingScript.Cirth ),
				new KeyValuePair<string,WritingScript>( "Copt", WritingScript.Coptic ),
				new KeyValuePair<string,WritingScript>( "Coptic", WritingScript.Coptic ),
				new KeyValuePair<string,WritingScript>( "Qaac", WritingScript.Coptic ),
				new KeyValuePair<string,WritingScript>( "Cprt", WritingScript.Cypriot ),
				new KeyValuePair<string,WritingScript>( "Cypriot", WritingScript.Cypriot ),
				new KeyValuePair<string,WritingScript>( "Cyrl", WritingScript.Cyrillic ),
				new KeyValuePair<string,WritingScript>( "Cyrillic", WritingScript.Cyrillic ),
				new KeyValuePair<string,WritingScript>( "Cyrs", WritingScript.CyrillicOldChurch ),
				new KeyValuePair<string,WritingScript>( "Deva", WritingScript.Devanagari ),
				new KeyValuePair<string,WritingScript>( "Devanagari", WritingScript.Devanagari ),
				new KeyValuePair<string,WritingScript>( "Dsrt", WritingScript.Deseret ),
				new KeyValuePair<string,WritingScript>( "Deseret", WritingScript.Deseret ),
				new KeyValuePair<string,WritingScript>( "Dupl", WritingScript.Duployan ),
				new KeyValuePair<string,WritingScript>( "Duployan", WritingScript.Duployan ),
				new KeyValuePair<string,WritingScript>( "Egyd", WritingScript.EgyptianDemotic ),
				new KeyValuePair<string,WritingScript>( "Egyh", WritingScript.EgyptianHieratic ),
				new KeyValuePair<string,WritingScript>( "Egyp", WritingScript.EgyptianHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Egyptian_Hieroglyphs", WritingScript.EgyptianHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Elba", WritingScript.Elbasan ),
				new KeyValuePair<string,WritingScript>( "Elbasan", WritingScript.Elbasan ),
				new KeyValuePair<string,WritingScript>( "Ethi", WritingScript.Ethiopic ),
				new KeyValuePair<string,WritingScript>( "Ethiopic", WritingScript.Ethiopic ),
				new KeyValuePair<string,WritingScript>( "Geok", WritingScript.Khutsuri ),
				new KeyValuePair<string,WritingScript>( "Geor", WritingScript.Georgian ),
				new KeyValuePair<string,WritingScript>( "Georgian", WritingScript.Georgian ),
				new KeyValuePair<string,WritingScript>( "Glag", WritingScript.Glagolitic ),
				new KeyValuePair<string,WritingScript>( "Glagolitic", WritingScript.Glagolitic ),
				new KeyValuePair<string,WritingScript>( "Goth", WritingScript.Gothic ),
				new KeyValuePair<string,WritingScript>( "Gothic", WritingScript.Gothic ),
				new KeyValuePair<string,WritingScript>( "Gran", WritingScript.Grantha ),
				new KeyValuePair<string,WritingScript>( "Grantha", WritingScript.Grantha ),
				new KeyValuePair<string,WritingScript>( "Grek", WritingScript.Greek ),
				new KeyValuePair<string,WritingScript>( "Greek", WritingScript.Greek ),
				new KeyValuePair<string,WritingScript>( "Gujr", WritingScript.Gujarati ),
				new KeyValuePair<string,WritingScript>( "Gujarati", WritingScript.Gujarati ),
				new KeyValuePair<string,WritingScript>( "Guru", WritingScript.Gurmukhi ),
				new KeyValuePair<string,WritingScript>( "Gurmukhi", WritingScript.Gurmukhi ),
				new KeyValuePair<string,WritingScript>( "Hanb", WritingScript.HanBopomofo ),
				new KeyValuePair<string,WritingScript>( "Hang", WritingScript.Hangul ),
				new KeyValuePair<string,WritingScript>( "Hangul", WritingScript.Hangul ),
				new KeyValuePair<string,WritingScript>( "Hani", WritingScript.Han ),
				new KeyValuePair<string,WritingScript>( "Han", WritingScript.Han ),
				new KeyValuePair<string,WritingScript>( "Hano", WritingScript.Hanunoo ),
				new KeyValuePair<string,WritingScript>( "Hanunoo", WritingScript.Hanunoo ),
				new KeyValuePair<string,WritingScript>( "Hans", WritingScript.HanSimplified ),
				new KeyValuePair<string,WritingScript>( "Hant", WritingScript.HanTraditional ),
				new KeyValuePair<string,WritingScript>( "Hatr", WritingScript.Hatran ),
				new KeyValuePair<string,WritingScript>( "Hatran", WritingScript.Hatran ),
				new KeyValuePair<string,WritingScript>( "Hebr", WritingScript.Hebrew ),
				new KeyValuePair<string,WritingScript>( "Hebrew", WritingScript.Hebrew ),
				new KeyValuePair<string,WritingScript>( "Hira", WritingScript.Hiragana ),
				new KeyValuePair<string,WritingScript>( "Hiragana", WritingScript.Hiragana ),
				new KeyValuePair<string,WritingScript>( "Hluw", WritingScript.AnatolianHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Anatolian_Hieroglyphs", WritingScript.AnatolianHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Hmng", WritingScript.PahawhHmong ),
				new KeyValuePair<string,WritingScript>( "Pahawh_Hmong", WritingScript.PahawhHmong ),
				new KeyValuePair<string,WritingScript>( "Hrkt", WritingScript.KatakanaOrHiragana ),
				new KeyValuePair<string,WritingScript>( "Katakana_Or_Hiragana", WritingScript.KatakanaOrHiragana ),
				new KeyValuePair<string,WritingScript>( "Hung", WritingScript.OldHungarian ),
				new KeyValuePair<string,WritingScript>( "Old_Hungarian", WritingScript.OldHungarian ),
				new KeyValuePair<string,WritingScript>( "Inds", WritingScript.IndusHarappan ),
				new KeyValuePair<string,WritingScript>( "Ital", WritingScript.OldItalic ),
				new KeyValuePair<string,WritingScript>( "Old_Italic", WritingScript.OldItalic ),
				new KeyValuePair<string,WritingScript>( "Jamo", WritingScript.Jamo ),
				new KeyValuePair<string,WritingScript>( "Java", WritingScript.Javanese ),
				new KeyValuePair<string,WritingScript>( "Javanese", WritingScript.Javanese ),
				new KeyValuePair<string,WritingScript>( "Jpan", WritingScript.HanHiraganaKatakana ),
				new KeyValuePair<string,WritingScript>( "Jurc", WritingScript.Jurchen ),
				new KeyValuePair<string,WritingScript>( "Kali", WritingScript.KayahLi ),
				new KeyValuePair<string,WritingScript>( "Kayah_Li", WritingScript.KayahLi ),
				new KeyValuePair<string,WritingScript>( "Kana", WritingScript.Katakana ),
				new KeyValuePair<string,WritingScript>( "Katakana", WritingScript.Katakana ),
				new KeyValuePair<string,WritingScript>( "Khar", WritingScript.Kharoshthi ),
				new KeyValuePair<string,WritingScript>( "Kharoshthi", WritingScript.Kharoshthi ),
				new KeyValuePair<string,WritingScript>( "Khmr", WritingScript.Khmer ),
				new KeyValuePair<string,WritingScript>( "Khmer", WritingScript.Khmer ),
				new KeyValuePair<string,WritingScript>( "Khoj", WritingScript.Khojki ),
				new KeyValuePair<string,WritingScript>( "Khojki", WritingScript.Khojki ),
				new KeyValuePair<string,WritingScript>( "Kitl", WritingScript.KhitanLargeScript ),
				new KeyValuePair<string,WritingScript>( "Kits", WritingScript.KhitanSmallScript ),
				new KeyValuePair<string,WritingScript>( "Knda", WritingScript.Kannada ),
				new KeyValuePair<string,WritingScript>( "Kannada", WritingScript.Kannada ),
				new KeyValuePair<string,WritingScript>( "Kore", WritingScript.HangulHan ),
				new KeyValuePair<string,WritingScript>( "Kpel", WritingScript.Kpelle ),
				new KeyValuePair<string,WritingScript>( "Kthi", WritingScript.Kaithi ),
				new KeyValuePair<string,WritingScript>( "Kaithi", WritingScript.Kaithi ),
				new KeyValuePair<string,WritingScript>( "Lana", WritingScript.TaiTham ),
				new KeyValuePair<string,WritingScript>( "Tai_Tham", WritingScript.TaiTham ),
				new KeyValuePair<string,WritingScript>( "Laoo", WritingScript.Lao ),
				new KeyValuePair<string,WritingScript>( "Lao", WritingScript.Lao ),
				new KeyValuePair<string,WritingScript>( "Latf", WritingScript.LatinFrakturVariant ),
				new KeyValuePair<string,WritingScript>( "Latg", WritingScript.LatinGaelicVariant ),
				new KeyValuePair<string,WritingScript>( "Latn", WritingScript.Latin ),
				new KeyValuePair<string,WritingScript>( "Latin", WritingScript.Latin ),
				new KeyValuePair<string,WritingScript>( "Leke", WritingScript.Leke ),
				new KeyValuePair<string,WritingScript>( "Lepc", WritingScript.Lepcha ),
				new KeyValuePair<string,WritingScript>( "Lepcha", WritingScript.Lepcha ),
				new KeyValuePair<string,WritingScript>( "Limb", WritingScript.Limbu ),
				new KeyValuePair<string,WritingScript>( "Limbu", WritingScript.Limbu ),
				new KeyValuePair<string,WritingScript>( "Lina", WritingScript.LinearA ),
				new KeyValuePair<string,WritingScript>( "Linear_A", WritingScript.LinearA ),
				new KeyValuePair<string,WritingScript>( "Linb", WritingScript.LinearB ),
				new KeyValuePair<string,WritingScript>( "Linear_B", WritingScript.LinearB ),
				new KeyValuePair<string,WritingScript>( "Lisu", WritingScript.Lisu ),
				new KeyValuePair<string,WritingScript>( "Loma", WritingScript.Loma ),
				new KeyValuePair<string,WritingScript>( "Lyci", WritingScript.Lycian ),
				new KeyValuePair<string,WritingScript>( "Lycian", WritingScript.Lycian ),
				new KeyValuePair<string,WritingScript>( "Lydi", WritingScript.Lydian ),
				new KeyValuePair<string,WritingScript>( "Lydian", WritingScript.Lydian ),
				new KeyValuePair<string,WritingScript>( "Mahj", WritingScript.Mahajani ),
				new KeyValuePair<string,WritingScript>( "Mahajani", WritingScript.Mahajani ),
				new KeyValuePair<string,WritingScript>( "Mand", WritingScript.Mandaic ),
				new KeyValuePair<string,WritingScript>( "Mandaic", WritingScript.Mandaic ),
				new KeyValuePair<string,WritingScript>( "Mani", WritingScript.Manichaean ),
				new KeyValuePair<string,WritingScript>( "Manichaean", WritingScript.Manichaean ),
				new KeyValuePair<string,WritingScript>( "Marc", WritingScript.Marchen ),
				new KeyValuePair<string,WritingScript>( "Maya", WritingScript.MayanHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Mend", WritingScript.MendeKikakui ),
				new KeyValuePair<string,WritingScript>( "Mende_Kikakui", WritingScript.MendeKikakui ),
				new KeyValuePair<string,WritingScript>( "Merc", WritingScript.MeroiticCursive ),
				new KeyValuePair<string,WritingScript>( "Meroitic_Cursive", WritingScript.MeroiticCursive ),
				new KeyValuePair<string,WritingScript>( "Mero", WritingScript.MeroiticHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Meroitic_Hieroglyphs", WritingScript.MeroiticHieroglyphs ),
				new KeyValuePair<string,WritingScript>( "Mlym", WritingScript.Malayalam ),
				new KeyValuePair<string,WritingScript>( "Malayalam", WritingScript.Malayalam ),
				new KeyValuePair<string,WritingScript>( "Modi", WritingScript.Modi ),
				new KeyValuePair<string,WritingScript>( "Mong", WritingScript.Mongolian ),
				new KeyValuePair<string,WritingScript>( "Mongolian", WritingScript.Mongolian ),
				new KeyValuePair<string,WritingScript>( "Moon", WritingScript.Moon ),
				new KeyValuePair<string,WritingScript>( "Mroo", WritingScript.Mro ),
				new KeyValuePair<string,WritingScript>( "Mro", WritingScript.Mro ),
				new KeyValuePair<string,WritingScript>( "Mtei", WritingScript.MeeteiMayek ),
				new KeyValuePair<string,WritingScript>( "Meetei_Mayek", WritingScript.MeeteiMayek ),
				new KeyValuePair<string,WritingScript>( "Mult", WritingScript.Multani ),
				new KeyValuePair<string,WritingScript>( "Multani", WritingScript.Multani ),
				new KeyValuePair<string,WritingScript>( "Mymr", WritingScript.Myanmar ),
				new KeyValuePair<string,WritingScript>( "Myanmar", WritingScript.Myanmar ),
				new KeyValuePair<string,WritingScript>( "Narb", WritingScript.OldNorthArabian ),
				new KeyValuePair<string,WritingScript>( "Old_North_Arabian", WritingScript.OldNorthArabian ),
				new KeyValuePair<string,WritingScript>( "Nbat", WritingScript.Nabataean ),
				new KeyValuePair<string,WritingScript>( "Nabataean", WritingScript.Nabataean ),
				new KeyValuePair<string,WritingScript>( "Newa", WritingScript.Newa ),
				new KeyValuePair<string,WritingScript>( "Nkgb", WritingScript.NakhiGeba ),
				new KeyValuePair<string,WritingScript>( "Nkoo", WritingScript.Nko ),
				new KeyValuePair<string,WritingScript>( "Nko", WritingScript.Nko ),
				new KeyValuePair<string,WritingScript>( "Nshu", WritingScript.Nushu ),
				new KeyValuePair<string,WritingScript>( "Ogam", WritingScript.Ogham ),
				new KeyValuePair<string,WritingScript>( "Ogham", WritingScript.Ogham ),
				new KeyValuePair<string,WritingScript>( "Olck", WritingScript.OlChiki ),
				new KeyValuePair<string,WritingScript>( "Ol_Chiki", WritingScript.OlChiki ),
				new KeyValuePair<string,WritingScript>( "Orkh", WritingScript.OldTurkic ),
				new KeyValuePair<string,WritingScript>( "Old_Turkic", WritingScript.OldTurkic ),
				new KeyValuePair<string,WritingScript>( "Orya", WritingScript.Oriya ),
				new KeyValuePair<string,WritingScript>( "Oriya", WritingScript.Oriya ),
				new KeyValuePair<string,WritingScript>( "Osge", WritingScript.Osage ),
				new KeyValuePair<string,WritingScript>( "Osma", WritingScript.Osmanya ),
				new KeyValuePair<string,WritingScript>( "Osmanya", WritingScript.Osmanya ),
				new KeyValuePair<string,WritingScript>( "Palm", WritingScript.Palmyrene ),
				new KeyValuePair<string,WritingScript>( "Palmyrene", WritingScript.Palmyrene ),
				new KeyValuePair<string,WritingScript>( "Pauc", WritingScript.PauCinHau ),
				new KeyValuePair<string,WritingScript>( "Pau_Cin_Hau", WritingScript.PauCinHau ),
				new KeyValuePair<string,WritingScript>( "Perm", WritingScript.OldPermic ),
				new KeyValuePair<string,WritingScript>( "Old_Permic", WritingScript.OldPermic ),
				new KeyValuePair<string,WritingScript>( "Phag", WritingScript.PhagsPa ),
				new KeyValuePair<string,WritingScript>( "Phags_Pa", WritingScript.PhagsPa ),
				new KeyValuePair<string,WritingScript>( "Phli", WritingScript.InscriptionalPahlavi ),
				new KeyValuePair<string,WritingScript>( "Inscriptional_Pahlavi", WritingScript.InscriptionalPahlavi ),
				new KeyValuePair<string,WritingScript>( "Phlp", WritingScript.PsalterPahlavi ),
				new KeyValuePair<string,WritingScript>( "Psalter_Pahlavi", WritingScript.PsalterPahlavi ),
				new KeyValuePair<string,WritingScript>( "Phlv", WritingScript.BookPahlavi ),
				new KeyValuePair<string,WritingScript>( "Phnx", WritingScript.Phoenician ),
				new KeyValuePair<string,WritingScript>( "Phoenician", WritingScript.Phoenician ),
				new KeyValuePair<string,WritingScript>( "Piqd", WritingScript.Klingon ),
				new KeyValuePair<string,WritingScript>( "Plrd", WritingScript.Miao ),
				new KeyValuePair<string,WritingScript>( "Miao", WritingScript.Miao ),
				new KeyValuePair<string,WritingScript>( "Prti", WritingScript.InscriptionalParthian ),
				new KeyValuePair<string,WritingScript>( "Inscriptional_Parthian", WritingScript.InscriptionalParthian ),
				new KeyValuePair<string,WritingScript>( "Qaaa", WritingScript.ReservedForPrivateUseStart ),
				new KeyValuePair<string,WritingScript>( "Qabx", WritingScript.ReservedForPrivateUseEnd ),
				new KeyValuePair<string,WritingScript>( "Rjng", WritingScript.Rejang ),
				new KeyValuePair<string,WritingScript>( "Rejang", WritingScript.Rejang ),
				new KeyValuePair<string,WritingScript>( "Roro", WritingScript.Rongorongo ),
				new KeyValuePair<string,WritingScript>( "Runr", WritingScript.Runic ),
				new KeyValuePair<string,WritingScript>( "Runic", WritingScript.Runic ),
				new KeyValuePair<string,WritingScript>( "Samr", WritingScript.Samaritan ),
				new KeyValuePair<string,WritingScript>( "Samaritan", WritingScript.Samaritan ),
				new KeyValuePair<string,WritingScript>( "Sara", WritingScript.Sarati ),
				new KeyValuePair<string,WritingScript>( "Sarb", WritingScript.OldSouthArabian ),
				new KeyValuePair<string,WritingScript>( "Old_South_Arabian", WritingScript.OldSouthArabian ),
				new KeyValuePair<string,WritingScript>( "Saur", WritingScript.Saurashtra ),
				new KeyValuePair<string,WritingScript>( "Saurashtra", WritingScript.Saurashtra ),
				new KeyValuePair<string,WritingScript>( "Sgnw", WritingScript.SignWriting ),
				new KeyValuePair<string,WritingScript>( "SignWriting", WritingScript.SignWriting ),
				new KeyValuePair<string,WritingScript>( "Shaw", WritingScript.Shavian ),
				new KeyValuePair<string,WritingScript>( "Shavian", WritingScript.Shavian ),
				new KeyValuePair<string,WritingScript>( "Shrd", WritingScript.Sharada ),
				new KeyValuePair<string,WritingScript>( "Sharada", WritingScript.Sharada ),
				new KeyValuePair<string,WritingScript>( "Sidd", WritingScript.Siddham ),
				new KeyValuePair<string,WritingScript>( "Siddham", WritingScript.Siddham ),
				new KeyValuePair<string,WritingScript>( "Sind", WritingScript.Khudawadi ),
				new KeyValuePair<string,WritingScript>( "Khudawadi", WritingScript.Khudawadi ),
				new KeyValuePair<string,WritingScript>( "Sinh", WritingScript.Sinhala ),
				new KeyValuePair<string,WritingScript>( "Sinhala", WritingScript.Sinhala ),
				new KeyValuePair<string,WritingScript>( "Sora", WritingScript.SoraSompeng ),
				new KeyValuePair<string,WritingScript>( "Sora_Sompeng", WritingScript.SoraSompeng ),
				new KeyValuePair<string,WritingScript>( "Sund", WritingScript.Sundanese ),
				new KeyValuePair<string,WritingScript>( "Sundanese", WritingScript.Sundanese ),
				new KeyValuePair<string,WritingScript>( "Sylo", WritingScript.SylotiNagri ),
				new KeyValuePair<string,WritingScript>( "Syloti_Nagri", WritingScript.SylotiNagri ),
				new KeyValuePair<string,WritingScript>( "Syrc", WritingScript.Syriac ),
				new KeyValuePair<string,WritingScript>( "Syriac", WritingScript.Syriac ),
				new KeyValuePair<string,WritingScript>( "Syre", WritingScript.SyriacEstrangelo ),
				new KeyValuePair<string,WritingScript>( "Syrj", WritingScript.SyriacWestern ),
				new KeyValuePair<string,WritingScript>( "Syrn", WritingScript.SyriacEastern ),
				new KeyValuePair<string,WritingScript>( "Tagb", WritingScript.Tagbanwa ),
				new KeyValuePair<string,WritingScript>( "Tagbanwa", WritingScript.Tagbanwa ),
				new KeyValuePair<string,WritingScript>( "Takr", WritingScript.Takri ),
				new KeyValuePair<string,WritingScript>( "Takri", WritingScript.Takri ),
				new KeyValuePair<string,WritingScript>( "Tale", WritingScript.TaiLe ),
				new KeyValuePair<string,WritingScript>( "Tai_Le", WritingScript.TaiLe ),
				new KeyValuePair<string,WritingScript>( "Talu", WritingScript.NewTaiLue ),
				new KeyValuePair<string,WritingScript>( "New_Tai_Lue", WritingScript.NewTaiLue ),
				new KeyValuePair<string,WritingScript>( "Taml", WritingScript.Tamil ),
				new KeyValuePair<string,WritingScript>( "Tamil", WritingScript.Tamil ),
				new KeyValuePair<string,WritingScript>( "Tang", WritingScript.Tangut ),
				new KeyValuePair<string,WritingScript>( "Tavt", WritingScript.TaiViet ),
				new KeyValuePair<string,WritingScript>( "Tai_Viet", WritingScript.TaiViet ),
				new KeyValuePair<string,WritingScript>( "Telu", WritingScript.Telugu ),
				new KeyValuePair<string,WritingScript>( "Telugu", WritingScript.Telugu ),
				new KeyValuePair<string,WritingScript>( "Teng", WritingScript.Tengwar ),
				new KeyValuePair<string,WritingScript>( "Tfng", WritingScript.Tifinagh ),
				new KeyValuePair<string,WritingScript>( "Tifinagh", WritingScript.Tifinagh ),
				new KeyValuePair<string,WritingScript>( "Tglg", WritingScript.Tagalog ),
				new KeyValuePair<string,WritingScript>( "Tagalog", WritingScript.Tagalog ),
				new KeyValuePair<string,WritingScript>( "Thaa", WritingScript.Thaana ),
				new KeyValuePair<string,WritingScript>( "Thaana", WritingScript.Thaana ),
				new KeyValuePair<string,WritingScript>( "Thai", WritingScript.Thai ),
				new KeyValuePair<string,WritingScript>( "Tibt", WritingScript.Tibetan ),
				new KeyValuePair<string,WritingScript>( "Tibetan", WritingScript.Tibetan ),
				new KeyValuePair<string,WritingScript>( "Tirh", WritingScript.Tirhuta ),
				new KeyValuePair<string,WritingScript>( "Tirhuta", WritingScript.Tirhuta ),
				new KeyValuePair<string,WritingScript>( "Ugar", WritingScript.Ugaritic ),
				new KeyValuePair<string,WritingScript>( "Ugaritic", WritingScript.Ugaritic ),
				new KeyValuePair<string,WritingScript>( "Vaii", WritingScript.Vai ),
				new KeyValuePair<string,WritingScript>( "Vai", WritingScript.Vai ),
				new KeyValuePair<string,WritingScript>( "Visp", WritingScript.VisibleSpeech ),
				new KeyValuePair<string,WritingScript>( "Wara", WritingScript.WarangCiti ),
				new KeyValuePair<string,WritingScript>( "Warang_Citi", WritingScript.WarangCiti ),
				new KeyValuePair<string,WritingScript>( "Wole", WritingScript.Woleai ),
				new KeyValuePair<string,WritingScript>( "Xpeo", WritingScript.OldPersian ),
				new KeyValuePair<string,WritingScript>( "Old_Persian", WritingScript.OldPersian ),
				new KeyValuePair<string,WritingScript>( "Xsux", WritingScript.Cuneiform ),
				new KeyValuePair<string,WritingScript>( "Cuneiform", WritingScript.Cuneiform ),
				new KeyValuePair<string,WritingScript>( "Yiii", WritingScript.Yi ),
				new KeyValuePair<string,WritingScript>( "Yi", WritingScript.Yi ),
				new KeyValuePair<string,WritingScript>( "Zinh", WritingScript.Inherited ),
				new KeyValuePair<string,WritingScript>( "Inherited", WritingScript.Inherited ),
				new KeyValuePair<string,WritingScript>( "Qaai", WritingScript.Inherited ),
				new KeyValuePair<string,WritingScript>( "Zmth", WritingScript.MathematicalNotation ),
				new KeyValuePair<string,WritingScript>( "Zsye", WritingScript.Emoji ),
				new KeyValuePair<string,WritingScript>( "Zsym", WritingScript.Symbols ),
				new KeyValuePair<string,WritingScript>( "Zxxx", WritingScript.UnwrittenDocuments ),
				new KeyValuePair<string,WritingScript>( "Zyyy", WritingScript.Common ),
				new KeyValuePair<string,WritingScript>( "Common", WritingScript.Common ),
				new KeyValuePair<string,WritingScript>( "Zzzz", WritingScript.Unknown ),
				new KeyValuePair<string,WritingScript>( "Unknown", WritingScript.Unknown )
			};
		}
		private static readonly Dictionary<short,string> _scriptCodes = new Dictionary<short,string>() {
			{ (short)WritingScript.Adlam, "Adlm" },
			{ (short)WritingScript.Afaka, "Afak" },
			{ (short)WritingScript.CaucasianAlbanian, "Aghb" },
			{ (short)WritingScript.Ahom, "Ahom" },
			{ (short)WritingScript.Arabic, "Arab" },
			{ (short)WritingScript.ArabicNastaliq, "Aran" },
			{ (short)WritingScript.ImperialAramaic, "Armi" },
			{ (short)WritingScript.Armenian, "Armn" },
			{ (short)WritingScript.Avestan, "Avst" },
			{ (short)WritingScript.Balinese, "Bali" },
			{ (short)WritingScript.Bamum, "Bamu" },
			{ (short)WritingScript.BassaVah, "Bass" },
			{ (short)WritingScript.Batak, "Batk" },
			{ (short)WritingScript.Bengali, "Beng" },
			{ (short)WritingScript.Bhaiksuki, "Bhks" },
			{ (short)WritingScript.Blissymbols, "Blis" },
			{ (short)WritingScript.Bopomofo, "Bopo" },
			{ (short)WritingScript.Brahmi, "Brah" },
			{ (short)WritingScript.Braille, "Brai" },
			{ (short)WritingScript.Buginese, "Bugi" },
			{ (short)WritingScript.Buhid, "Buhd" },
			{ (short)WritingScript.Chakma, "Cakm" },
			{ (short)WritingScript.CanadianAboriginal, "Cans" },
			{ (short)WritingScript.Carian, "Cari" },
			{ (short)WritingScript.Cham, "Cham" },
			{ (short)WritingScript.Cherokee, "Cher" },
			{ (short)WritingScript.Cirth, "Cirt" },
			{ (short)WritingScript.Coptic, "Copt" },
			{ (short)WritingScript.Cypriot, "Cprt" },
			{ (short)WritingScript.Cyrillic, "Cyrl" },
			{ (short)WritingScript.CyrillicOldChurch, "Cyrs" },
			{ (short)WritingScript.Devanagari, "Deva" },
			{ (short)WritingScript.Deseret, "Dsrt" },
			{ (short)WritingScript.Duployan, "Dupl" },
			{ (short)WritingScript.EgyptianDemotic, "Egyd" },
			{ (short)WritingScript.EgyptianHieratic, "Egyh" },
			{ (short)WritingScript.EgyptianHieroglyphs, "Egyp" },
			{ (short)WritingScript.Elbasan, "Elba" },
			{ (short)WritingScript.Ethiopic, "Ethi" },
			{ (short)WritingScript.Khutsuri, "Geok" },
			{ (short)WritingScript.Georgian, "Geor" },
			{ (short)WritingScript.Glagolitic, "Glag" },
			{ (short)WritingScript.Gothic, "Goth" },
			{ (short)WritingScript.Grantha, "Gran" },
			{ (short)WritingScript.Greek, "Grek" },
			{ (short)WritingScript.Gujarati, "Gujr" },
			{ (short)WritingScript.Gurmukhi, "Guru" },
			{ (short)WritingScript.HanBopomofo, "Hanb" },
			{ (short)WritingScript.Hangul, "Hang" },
			{ (short)WritingScript.Han, "Hani" },
			{ (short)WritingScript.Hanunoo, "Hano" },
			{ (short)WritingScript.HanSimplified, "Hans" },
			{ (short)WritingScript.HanTraditional, "Hant" },
			{ (short)WritingScript.Hatran, "Hatr" },
			{ (short)WritingScript.Hebrew, "Hebr" },
			{ (short)WritingScript.Hiragana, "Hira" },
			{ (short)WritingScript.AnatolianHieroglyphs, "Hluw" },
			{ (short)WritingScript.PahawhHmong, "Hmng" },
			{ (short)WritingScript.KatakanaOrHiragana, "Hrkt" },
			{ (short)WritingScript.OldHungarian, "Hung" },
			{ (short)WritingScript.IndusHarappan, "Inds" },
			{ (short)WritingScript.OldItalic, "Ital" },
			{ (short)WritingScript.Jamo, "Jamo" },
			{ (short)WritingScript.Javanese, "Java" },
			{ (short)WritingScript.HanHiraganaKatakana, "Jpan" },
			{ (short)WritingScript.Jurchen, "Jurc" },
			{ (short)WritingScript.KayahLi, "Kali" },
			{ (short)WritingScript.Katakana, "Kana" },
			{ (short)WritingScript.Kharoshthi, "Khar" },
			{ (short)WritingScript.Khmer, "Khmr" },
			{ (short)WritingScript.Khojki, "Khoj" },
			{ (short)WritingScript.KhitanLargeScript, "Kitl" },
			{ (short)WritingScript.KhitanSmallScript, "Kits" },
			{ (short)WritingScript.Kannada, "Knda" },
			{ (short)WritingScript.HangulHan, "Kore" },
			{ (short)WritingScript.Kpelle, "Kpel" },
			{ (short)WritingScript.Kaithi, "Kthi" },
			{ (short)WritingScript.TaiTham, "Lana" },
			{ (short)WritingScript.Lao, "Laoo" },
			{ (short)WritingScript.LatinFrakturVariant, "Latf" },
			{ (short)WritingScript.LatinGaelicVariant, "Latg" },
			{ (short)WritingScript.Latin, "Latn" },
			{ (short)WritingScript.Leke, "Leke" },
			{ (short)WritingScript.Lepcha, "Lepc" },
			{ (short)WritingScript.Limbu, "Limb" },
			{ (short)WritingScript.LinearA, "Lina" },
			{ (short)WritingScript.LinearB, "Linb" },
			{ (short)WritingScript.Lisu, "Lisu" },
			{ (short)WritingScript.Loma, "Loma" },
			{ (short)WritingScript.Lycian, "Lyci" },
			{ (short)WritingScript.Lydian, "Lydi" },
			{ (short)WritingScript.Mahajani, "Mahj" },
			{ (short)WritingScript.Mandaic, "Mand" },
			{ (short)WritingScript.Manichaean, "Mani" },
			{ (short)WritingScript.Marchen, "Marc" },
			{ (short)WritingScript.MayanHieroglyphs, "Maya" },
			{ (short)WritingScript.MendeKikakui, "Mend" },
			{ (short)WritingScript.MeroiticCursive, "Merc" },
			{ (short)WritingScript.MeroiticHieroglyphs, "Mero" },
			{ (short)WritingScript.Malayalam, "Mlym" },
			{ (short)WritingScript.Modi, "Modi" },
			{ (short)WritingScript.Mongolian, "Mong" },
			{ (short)WritingScript.Moon, "Moon" },
			{ (short)WritingScript.Mro, "Mroo" },
			{ (short)WritingScript.MeeteiMayek, "Mtei" },
			{ (short)WritingScript.Multani, "Mult" },
			{ (short)WritingScript.Myanmar, "Mymr" },
			{ (short)WritingScript.OldNorthArabian, "Narb" },
			{ (short)WritingScript.Nabataean, "Nbat" },
			{ (short)WritingScript.Newa, "Newa" },
			{ (short)WritingScript.NakhiGeba, "Nkgb" },
			{ (short)WritingScript.Nko, "Nkoo" },
			{ (short)WritingScript.Nushu, "Nshu" },
			{ (short)WritingScript.Ogham, "Ogam" },
			{ (short)WritingScript.OlChiki, "Olck" },
			{ (short)WritingScript.OldTurkic, "Orkh" },
			{ (short)WritingScript.Oriya, "Orya" },
			{ (short)WritingScript.Osage, "Osge" },
			{ (short)WritingScript.Osmanya, "Osma" },
			{ (short)WritingScript.Palmyrene, "Palm" },
			{ (short)WritingScript.PauCinHau, "Pauc" },
			{ (short)WritingScript.OldPermic, "Perm" },
			{ (short)WritingScript.PhagsPa, "Phag" },
			{ (short)WritingScript.InscriptionalPahlavi, "Phli" },
			{ (short)WritingScript.PsalterPahlavi, "Phlp" },
			{ (short)WritingScript.BookPahlavi, "Phlv" },
			{ (short)WritingScript.Phoenician, "Phnx" },
			{ (short)WritingScript.Klingon, "Piqd" },
			{ (short)WritingScript.Miao, "Plrd" },
			{ (short)WritingScript.InscriptionalParthian, "Prti" },
			{ (short)WritingScript.ReservedForPrivateUseStart, "Qaaa" },
			{ (short)WritingScript.ReservedForPrivateUseEnd, "Qabx" },
			{ (short)WritingScript.Rejang, "Rjng" },
			{ (short)WritingScript.Rongorongo, "Roro" },
			{ (short)WritingScript.Runic, "Runr" },
			{ (short)WritingScript.Samaritan, "Samr" },
			{ (short)WritingScript.Sarati, "Sara" },
			{ (short)WritingScript.OldSouthArabian, "Sarb" },
			{ (short)WritingScript.Saurashtra, "Saur" },
			{ (short)WritingScript.SignWriting, "Sgnw" },
			{ (short)WritingScript.Shavian, "Shaw" },
			{ (short)WritingScript.Sharada, "Shrd" },
			{ (short)WritingScript.Siddham, "Sidd" },
			{ (short)WritingScript.Khudawadi, "Sind" },
			{ (short)WritingScript.Sinhala, "Sinh" },
			{ (short)WritingScript.SoraSompeng, "Sora" },
			{ (short)WritingScript.Sundanese, "Sund" },
			{ (short)WritingScript.SylotiNagri, "Sylo" },
			{ (short)WritingScript.Syriac, "Syrc" },
			{ (short)WritingScript.SyriacEstrangelo, "Syre" },
			{ (short)WritingScript.SyriacWestern, "Syrj" },
			{ (short)WritingScript.SyriacEastern, "Syrn" },
			{ (short)WritingScript.Tagbanwa, "Tagb" },
			{ (short)WritingScript.Takri, "Takr" },
			{ (short)WritingScript.TaiLe, "Tale" },
			{ (short)WritingScript.NewTaiLue, "Talu" },
			{ (short)WritingScript.Tamil, "Taml" },
			{ (short)WritingScript.Tangut, "Tang" },
			{ (short)WritingScript.TaiViet, "Tavt" },
			{ (short)WritingScript.Telugu, "Telu" },
			{ (short)WritingScript.Tengwar, "Teng" },
			{ (short)WritingScript.Tifinagh, "Tfng" },
			{ (short)WritingScript.Tagalog, "Tglg" },
			{ (short)WritingScript.Thaana, "Thaa" },
			{ (short)WritingScript.Thai, "Thai" },
			{ (short)WritingScript.Tibetan, "Tibt" },
			{ (short)WritingScript.Tirhuta, "Tirh" },
			{ (short)WritingScript.Ugaritic, "Ugar" },
			{ (short)WritingScript.Vai, "Vaii" },
			{ (short)WritingScript.VisibleSpeech, "Visp" },
			{ (short)WritingScript.WarangCiti, "Wara" },
			{ (short)WritingScript.Woleai, "Wole" },
			{ (short)WritingScript.OldPersian, "Xpeo" },
			{ (short)WritingScript.Cuneiform, "Xsux" },
			{ (short)WritingScript.Yi, "Yiii" },
			{ (short)WritingScript.Inherited, "Zinh" },
			{ (short)WritingScript.MathematicalNotation, "Zmth" },
			{ (short)WritingScript.Emoji, "Zsye" },
			{ (short)WritingScript.Symbols, "Zsym" },
			{ (short)WritingScript.UnwrittenDocuments, "Zxxx" },
			{ (short)WritingScript.Common, "Zyyy" },
			{ (short)WritingScript.Unknown, "Zzzz" }
		};
	}
}
